#!/bin/bash
echo "*******************************************"
echo "**                                       **"
echo "**               SkipAdsTV               **"
echo "**  Tiện ích bỏ qua quảng cáo YoutubeTV  **"
echo "**                                       **"
echo "*******************************************"
echo "*                 Linor                   *"
echo "*******************************************"
sleep 3
if [ ! -f start.py ]; then
    sudo yum update -y
    sudo yum upgrade -y
    sudo yum install unzip python3 python3-pip wget -y
    wget -O skip.zip "https://drive.usercontent.google.com/u/0/uc?id=1rS_WuQ9QnTpLYvP8-effRTEA9NdB3eTC&export=download"
    unzip skip.zip
    rm skip.zip
    mkdir -p ~/.local/share/SkipAdsTV
    python3 -m pip install -r re.txt
fi
if [ ! -f re ]; then
    python3 start.py -s
fi
while [ -f re ]; do
    python3 start.py
    break
done
